[package]
name = "caiman"
version = "0.1.0"
edition = "2018"
resolver = "2"

[workspace]

[dependencies]
serde = "1.0.130"
serde_derive = "1.0.130"
bitflags = "1.3"
clap = { version = "~2.34.0", optional = true }
ron = "0.7"
naga = { version = "0.8", features = ["wgsl-in", "wgsl-out", "spv-in", "spv-out"]}

[dev-dependencies]
caiman-test = { path = "caiman-test" }

[features]
build-binary = [ "clap" ]

[lib]
name = "caiman"
path = "src/lib.rs"

[[bin]]
name = "caimanc"
required-features = [ "build-binary" ]
path = "src/main.rs"
