[package]
name = "caiman"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0.130"
serde_derive = "1.0.130"
bitflags = "1.3"
toml = { version = "0.5", optional = true }
clap = { version = "~2.33.3", optional = true }

[features]
build-binary = [ "toml", "clap" ]

[lib]
name = "caiman"
path = "src/lib.rs"

[[bin]]
name = "caimanc"
required-features = [ "build-binary" ]
path = "src/main.rs"