command = """\
"mkdir" -p debug && \
cat ../src/test_data1.txt > ../src/bin/{args}_{base}.rs && \
printf '{args}_{base}' >> ../src/bin/{args}_{base}.rs && \
cat ../src/test_data2.txt >> ../src/bin/{args}_{base}.rs && \
cat {base}.rs >> ../src/bin/{args}_{base}.rs && \
cargo run --manifest-path ../../Cargo.toml --features=build-binary -- \
--input {filename} --output ../src/bin/{args}_{base}_generated.rs > debug/{base}.log && \
cargo run --manifest-path ../Cargo.toml --bin {args}_{base} 2> debug/{base}.debug \
"""