[types]
#[types.Float32]
#Float32 = {}
t1 = { Array = {element_type = "Float32", length = 3} }
t2 = { ConstSlice = {element_type = "t1"} }
[pipelines]
[pipelines.draw_triangle]
#[pipelines.draw_triangle.variables]
variables = { vertices = { type_name = "t2" }, output_image = { type_name = "Image" }}
#[pipelines.draw_triangle]
arguments = [ "vertices", "output_image" ]
instructions = [
	{ GpuRasterCall = {} }
]
	#{ GpuRasterCall = {} }
#]
