[envs.expected]
command = "..\\..\\target\\debug\\caimanc.exe --input {base}_baseline.cair --explicate_only"

[envs.explicate]
command = "..\\..\\target\\debug\\caimanc.exe --input {filename} --explicate_only"