use crate::scheduling_language::ast::*;
use crate::scheduling_language::ast_factory::ASTFactory;

grammar(astf: &ASTFactory);

match {
  r"[a-zA-Z][a-zA-Z0-9_]*", // Id

  ";",

  r"\s*" => { }, // Whitespace
  r"//[^\n\r]*[\n\r]*" => { }, // Double-slash comments
}

pub Program: ParsedProgram = { Stmt* => <> }

pub Stmt: ParsedStmt = {
  <@L> <Id> ";" <@R> => astf.var(<>),
}

Id: String = { r"[a-zA-Z][a-zA-Z0-9_]*" => String::from(<>) }
