command = "cargo run --manifest-path ../../Cargo.toml --features=build-binary -- --input {filename} --output ../src/_generated.rs > {base}.log && cat {base}.rs > ../src/main.rs && cargo run --manifest-path ../Cargo.toml"
