command = """
cargo run --manifest-path ../../Cargo.toml --features=build-binary -- --input {filename} --output ../src/bin/{base}_generated.rs > {base}.log
cat ../src/test_data1.txt > ../src/bin/{base}.rs
printf '{base}' >> ../src/bin/{base}.rs
cat ../src/test_data2.txt >> ../src/bin/{base}.rs
cat {base}.rs >> ../src/bin/{base}.rs
cargo run --manifest-path ../Cargo.toml --bin {base}
"""
