command = """
cargo run --manifest-path ../../Cargo.toml --features=build-binary -- --input {filename} --output ../src/bin/{base}_generated.rs > {base}.log
cat ../src/test_data1.txt > ../src/bin/{base}.rs

echo '#![allow(warnings)]' > ../src/bin/{base}.rs
echo 'mod pipeline {{ include!("{base}_generated.rs"); }}' >> ../src/bin/{base}.rs

cat {base}.rs >> ../src/bin/{base}.rs
cargo run --manifest-path ../Cargo.toml --bin {base}
"""
