[package]
name = "caiman-demo"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
futures = "0.3"
caiman-rt = { path = "../caiman-rt" }
once_cell = "1.17.1"
file_diff = "1.0.0"

[lib]
name = "demo"
path = "src/lib.rs"