#version 450

layout(set = 0, binding = 0) readonly buffer Input_0 {
    int field_0;
    int field_1;
    int field_2;
    int field_3;
} input_0;

layout(set = 0, binding = 1) buffer Output_0 {
    int field_0;
} output_0;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{
    output_0.field_0 = input_0.field_0 + input_0.field_1 + input_0.field_2 + input_0.field_3;
}