[package]
name = "caiman-demo"
version = "0.1.0"
edition = "2018"
resolver = "2"

[build-dependencies]
caiman = { path = "../", features = ["build-binary"] }
ron = "0.7"

[dependencies]
wgpu = "0.12.0"
futures = "0.3"
