name: test
on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build
      - name: Format
        run: cargo fmt --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D clippy::suspicious -W clippy::all -D clippy::correctness
      - name: Test
        run: |
          python3 ./caiman-test/test.py run
