name: test
on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Weird Hacks
        run: |
          echo "#\![rustfmt::skip]\n" > caiman-test/src/lib.rs
      - name: Format
        run: cargo fmt --check --all
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D clippy::suspicious -W clippy::all -D clippy::correctness
      - name: Test
        run: |
          python3 ./caiman-test/test.py run
